### ISSUE TITLE
"Account Details" hangs

### ISSUE THREAD

**Issue by jawaidbazyar** [2600hz/kazoo-ui#29]
Fresh 3.19 install, kazoo-ui 3.19 3, as superduperuser, clicking "account details" hangs - as a sub-account, the GUI is non-responsive (i.e., menu disappears, no action is taken).

All I see in 2600hz.log is:

Mar 25 15:13:11 kz1 2600hz[3477]: |b25db828bca396be6b28372fd2016879|api_resource:105 (<0.22113.61>) GET: /v1/accounts/092b4738638519882f1ac548621edb19/media?_=1427317991636 from 216.241.37.98

**Comment by jawaidbazyar** [comment]
oops, turned on config.ini debug and get this:

It's failing trying to do a blacklists api call.

Notably, the Blacklists menu item also fails.


Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_resource:105 (<0.4234.0>) GET: /v1/accounts/092b4738638519882f1ac548621edb19/blacklists?_=1427320326586 from 216.241.37.98
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_resource:160 (<0.4234.0>) run: known_methods
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_resource:180 (<0.4234.0>) run: allowed_methods
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_util:147 (<0.4234.0>) query string: <<"{\"_\":\"1427320326586\"}">>
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_util:183 (<0.4234.0>) application/json content type when getting req data
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_resource:223 (<0.4234.0>) adding cors headers
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_resource:244 (<0.4234.0>) no allow methods
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_util:1090 (<0.4234.0>) halting execution here
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_util:1047 (<0.4234.0>) generating error 404 not found response
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_util:1093 (<0.4234.0>) setting resp body: {"data":{},"error":"404","message":"not found","status":"error","request_id":"e007f8601a6baf2e9c732661b0a305ad","auth_token":""}
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_util:1097 (<0.4234.0>) ensured CORS headers are on the response
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_util:1099 (<0.4234.0>) setting status code: 404
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|api_resource:149 (<0.4234.0>) GET request fulfilled in 1 ms
Mar 25 15:52:06 kz2 2600hz[19588]: |e007f8601a6baf2e9c732661b0a305ad|crossbar:38 (<0.4234.0>) routing to version 1

**Comment by JRMaitre** [comment]
Please file tickets in JIRA and not on our github! Thank you
